name: Subgraph Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build subgraph code
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        network: ['gnosis']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm install

      - name: Compile schema for specific network
        env:
          NETWORK: ${{ matrix.network }}
        run: |
          NETWORK=${{ env.NETWORK }} npm run define

      - name: Generate assembly script types
        run: |
          npm run codegen

      - name: Build wasm build for IPFS via graph-cli
        run: |
          npm run build

      - name: Deploy subgraph to legacy explorer
        env:
          NETWORK: ${{ matrix.network }}
        run: |
          npm run deploy -- onposter/${{ env.NETWORK }} --accessToken ${{ secrets.THEGRAPH_LEGACY_ACCESS_TOKEN }}
